### ISSUE TITLE
Event callback is not triggered

### ISSUE THREAD

**Issue by ghost** [kendagriff/workflow.js#1]
In following example onSignUp callback is not triggered.

<pre>
class User extends Backbone.Model
  defaults:
    signed_up_at: null

  workflow:
    initial: 'visitor'
    events: [
      { name: 'signUp', from: 'visitor', to: 'user' }
      { name: 'bail', from: 'visitor', to: 'lostUser' }
      { name: 'closeAccount', from: 'user', to: 'visitor' }
      { name: 'promote', from: 'user', to: 'superUser' }
    ]

  initialize: =>
    _.extend @, new Backbone.Workflow(@)

  onSignUp: =>
    @set { signed_up_at: new Date() }

user = new User()
user.get('workflow_state') # => "visitor"

user.triggerEvent('signUp')
user.get('workflow_state') # => "user"
user.get('signed_up_at') # => Fri Feb 17 2012 17:07:41 GMT-0700 (MST)
</pre>

See  https://github.com/kendagriff/workflow.js#usage

**Comment by ghost** [comment]
There is no any code to trigger such event.

**Comment by kendagriff** [comment]
Workflow.js is self-aware of its transitions. So, `onSignUp` should be called by virtue of the fact that you declared this transition:

```
events: [
      { name: 'signUp', from: 'visitor', to: 'user' }
]
```

Is it not working?

**Comment by ghost** [comment]
Hi,

Yes. Everything works fine except onSignup.

Actually the code I am using is:

<pre>
  // Create new model.
  var InvoiceModel = Backbone.Model.extend({
    
    // Define workflow states.
    workflow: {
      // Define initial state.
      initial: 'draft',
      // Define state transitions.
      events: [
        { name: 'issue', from: 'draft', to: 'issued' },
        { name: 'payout', from: 'issued', to: 'paid' },
        { name: 'cancel', from: 'draft', to: 'canceled' },
        { name: 'cancel', from: 'issued', to: 'canceled' },
      ]
    },
   onIssue: function() {
    alert('!!!');
   }
   initialize: function() {
      _.extend(this, new Backbone.Workflow(this, {attrName: 'status'}));
    }
  });
</pre>

onIssue is never called, unless I add event binding manually:

<pre>
  // Bind reaction on event when status changes from any to paid.
  this.bind('transition:to:issued', this.onIssue);
</pre>

I looked trhough the source and there is no reason onSignUp or onIssue to be called.

**Comment by kendagriff** [comment]
Great catch. I'll update the documentation. Looking back at my own projects, your implementation is the same as my own design. Thanks!
